[package]
name = "cardano-xprv-decode"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2", features = [ "derive" ]}
cryptoxide = { version = "0.4.2" }
hex = { version = "0.4" }